### ISSUE TITLE
flow type for material-ui already exisits

### ISSUE THREAD

**Issue by stunaz** [wcandillon/material-ui-flow#2]
> This is an attempt to build Flow types for material-ui that are more precise than the one built in the flow-typed repository. I'm looking for help to map some TypeScript types to Flow.

Why dont you juste submit pull request to the one built in the flow-typed repository?

**Comment by wcandillon** [comment]
the problem is that there doesn’t seem to be way with flow typed at the
moment to split the definition into multiple types and to depend on other
flow definitions (like csstype)
